spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bilheteira?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver


jwt:
  header: "Authentication"
  key: "#@%@$TGWSDFADG#^#$@#ASDaff#$14648124@#"
  issure: "D_M_P_W" #David Mariana Pedro Wei
  expiration: 3600  #1 hour
  expiration_remember: 604800 #7 days
